baseURL = "https://timedilationv2.github.io/checkcheck/"
languageCode = "en-us"
title = "SuperAi"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  author = "Arsalan Khan"
  description = "A blog about AI, systems, and thought."
  ShowReadingTime = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[markup]
  [markup.goldmark.renderer]
    unsafe = true
